LOCAL_PATH := $(call my-dir)
include $(CLEAR_VARS)

LOCAL_PACKAGE_NAME := SystemUIOverlaySweet
LOCAL_MODULE_PATH := $(TARGET_OUT_PRODUCT)/overlay/$(LOCAL_PACKAGE_NAME)
LOCAL_SDK_VERSION := current
LOCAL_IS_RUNTIME_RESOURCE_OVERLAY := true
LOCAL_RESOURCE_DIR := \
    $(LOCAL_PATH)/res

include $(BUILD_PACKAGE)
